### ISSUE TITLE
Comparison with git-annex?

### ISSUE THREAD

**Issue by alphapapa** [raxod502/madeline#1]
Hi,

This looks interesting.  Having followed Joey Hess's git-annex project for a few years, I wonder how it compares with it.  What do you think?

**Comment by raxod502** [comment]
I have not used git-annex, so the following analysis may be slightly erroneous. I did my best; let me know if you have other questions :)

---

* git-annex uses Git, obviously. It assumes that you are interested in some sort of version control, at least for metadata even if not for file contents.
* Madeline has no integration or support whatsoever for Git. It is a tool for moving files between two directory trees and nothing more. This obviously means it is simpler: just an 800-line Python script.

---

* git-annex has support for storing multiple copies of files in different remote storage locations, and keeping track of where they are. I believe you can also have a file both locally and remotely.
* Madeline is a tool for moving files between _exactly two_ directory trees and nothing more. The fact that it is disallowed to ever have a copy of the same file in both locations is not a limitation, but an explicit feature.

---

I think that Madeline would be better than git-annex for the use case of moving directories with a large number of descendent filesystem entries to a remote volume so that local backups with Borg are faster. That is my use case.

If you are already using git-annex for something, though, then git-annex is probably a better tool for it than Madeline.
